### ISSUE TITLE
Define new category.

### ISSUE THREAD

**Issue by niluxv** [saschagrunert/git-journal#287]
Citing from rfc-0001:
> It is also possible to define own categories.

But I can't find documentation on how to do this. Am I missing something?

**Comment by saschagrunert** [comment]
Hey @niluxv, it should be possible to define a new category via the configuration file:

https://github.com/saschagrunert/git-journal/blob/8614adaddfbe4bd6e5dfd6e7322f8980d379f28e/.gitjournal.toml#L1

**Comment by niluxv** [comment]
Ah, thank you.

**Comment by saschagrunert** [comment]
No worries, thanks for asking! :)
