### ISSUE TITLE
Add support for using lightweight tags in a revision range

### ISSUE THREAD

**Issue by ghost** [saschagrunert/git-journal#3]
Currently it is not possible to use lightweight tags in the revision range specification. It would be great if you can add this feature.

**Comment by saschagrunert** [comment]
Lightweight git tags are no real git objects, but more pointer to objects. The main tag retrieval logic is located [here](https://github.com/saschagrunert/git-journal/blob/master/src/lib.rs#L122-L130). I am currently not sure if [`tag_names()`](https://docs.rs/git2/0.6.6/git2/struct.Repository.html#method.tag_names) returns the lightweight tags too or not. But maybe we have to add additional logic here.
