### ISSUE TITLE
Add support for 'history simplification'

### ISSUE THREAD

**Issue by pJunger** [saschagrunert/git-journal#453]
Hello,

most Git commands support specifying a path as last argument [to restrict the scope of the command](https://git-scm.com/docs/git-log#_history_simplification).
This would be very helpful for cases where multiple applications live in the same repository.

e.g.
`git journal -a -- .`

Do you think it makes sense to provide this or should this be handled by tags in you opinion?

**Comment by saschagrunert** [comment]
Hm, yeah I think this would make sense... How would you handle it via tags?

**Comment by pJunger** [comment]
Well I wouldn't really. You would need to tag each commit and filter everything else out (since there doesn't seem to be a positive-filter), but that would be a poor-man's solution.

**Comment by saschagrunert** [comment]
> Well I wouldn't really. You would need to tag each commit and filter everything else out (since there doesn't seem to be a positive-filter), but that would be a poor-man's solution.

I agree. Would you mind opening a PR for that? :)

**Comment by pJunger** [comment]
I haven't worked with libgit2 yet, but I can see if I find the time :)
