### ISSUE TITLE
git-journal fails if TERM env variable is not set

### ISSUE THREAD

**Issue by pJunger** [saschagrunert/git-journal#464]
Logging and thus git-journal fails on initialization if TERM env variable is not set.
The underlying reason can be seen in https://github.com/saschagrunert/mowl/pull/1.

**Comment by saschagrunert** [comment]
Hey, thank you for the report. I’ll check if I can update mowl here in some time.

**Comment by pJunger** [comment]
I think that mowl isn't the only problem here - the lib itself initializes a terminal using the term::stdout function if I'm not mistaken. This should lead to the same problem (and I think ideally this should be fixed upstream, but well ...)

**Comment by saschagrunert** [comment]
I pushed a new version of mowl which should get picked-up by dependabot today.
