### ISSUE TITLE
Output to file and terminal

### ISSUE THREAD

**Issue by pJunger** [saschagrunert/git-journal#465]
Hey,

does it make sense to always output to the terminal, even if the output option is set?
Would you be open to having either 'xor' behavior or an additional 'quiet' flag to suppress the terminal output?

**Comment by saschagrunert** [comment]
Hey, what is the reason that you do not want output to the terminal?

(Beside the crash you’ve found. 🤭)

**Comment by pJunger** [comment]
Yeah I mean the crash was my first reason to look into that, but on the CI (where the crash happened) I want to see logging information (and lots of it) without anything else. The output that's written to the file is stored anyway, so I can look up the artifact later on if it matters to me.

Currently I just call `git journal .. > /dev/null`, but I also like to leave out the shell from the CI command.

**Comment by saschagrunert** [comment]
I see, do you want to spin-up a PR for that? :)

**Comment by pJunger** [comment]
Sure, I'll try to get it done. Which option do you prefer?

**Comment by saschagrunert** [comment]
I think the mentioned xor behavior would be fine, right?
