### ISSUE TITLE
Add support for passing config option via the CLI

### ISSUE THREAD

**Issue by ghost** [saschagrunert/git-journal#5]
It would be a nice to overwrite configuration options via the command line interface. I need this feature for an Emacs/Magit extension. I must fully disable the debug and color output, without changing the 'enable_debug' and 'colored_output' values of the project config. 

Do you think it is possible to add this feature?

**Comment by saschagrunert** [comment]
I guess this issue references #2. This can be done easily by adding additional command line parameters and setting them in the configuration. Are you willing to contribute for this?

**Comment by niko2342** [comment]
Yes, i can try to solve the issue.

**Comment by saschagrunert** [comment]
Sounds great, thanks
